app_homepage:
  resource: "@AppBundle/Controller/Article/"
  type:     annotation
  prefix:   /article
home:
  resource: "@AppBundle/Controller/HomeController.php"
  type: annotation
films:
  resource: "@AppBundle/Controller/films"
  type:     annotation
  prefix:   /films